g++ -I./ -c -o init_ENCRYPT.o init_ENCRYPT.cc
g++ -I./ -c -o decode_69.o decode_69.cc
g++ -I./ -c -o decode_106.o decode_106.cc
g++ -I./ -c -o decode_142.o decode_142.cc
g++ -I./ -c -o decode_419.o decode_419.cc
g++ -I./ -c -o decode_441.o decode_441.cc
g++ -I./ -c -o decode_69_update_TEST_address.o decode_69_update_TEST_address.cc
g++ -I./ -c -o decode_69_update_TEST_flag.o decode_69_update_TEST_flag.cc
g++ -I./ -c -o decode_106_update_TEST_status.o decode_106_update_TEST_status.cc
g++ -I./ -c -o decode_142_update_ENCRYPT_byte_cnt.o decode_142_update_ENCRYPT_byte_cnt.cc
g++ -I./ -c -o decode_142_update_ENCRYPT_rd_data.o decode_142_update_ENCRYPT_rd_data.cc
g++ -I./ -c -o decode_142_update_TEST_status.o decode_142_update_TEST_status.cc
g++ -I./ -c -o decode_419_update_ENCRYPT_enc_data.o decode_419_update_ENCRYPT_enc_data.cc
g++ -I./ -c -o decode_419_update_TEST_status.o decode_419_update_TEST_status.cc
g++ -I./ -c -o decode_441_update_TEST_XRAM.o decode_441_update_TEST_XRAM.cc
g++ -I./ -c -o decode_441_update_ENCRYPT_blk_cnt.o decode_441_update_ENCRYPT_blk_cnt.cc
g++ -I./ -c -o decode_441_update_ENCRYPT_byte_cnt.o decode_441_update_ENCRYPT_byte_cnt.cc
g++ -I./ -c -o decode_441_update_TEST_status.o decode_441_update_TEST_status.cc
g++ -I./ -c -o compute.o compute.cc 
g++ -I./ -c -o help.o ../../uninterpreted_func/uninterpreted_func.cc 
