g++ -I./ -c -o init_ENCRYPT.o init_ENCRYPT.cc
g++ -I./ -c -o decode_TEST_WRITE_ADDRESS.o decode_TEST_WRITE_ADDRESS.cc
g++ -I./ -c -o decode_TEST_START_ENCRYPT.o decode_TEST_START_ENCRYPT.cc
g++ -I./ -c -o decode_ENCRYPT_LOAD.o decode_ENCRYPT_LOAD.cc
g++ -I./ -c -o decode_ENCRYPT_ENC.o decode_ENCRYPT_ENC.cc
g++ -I./ -c -o decode_ENCRYPT_STORE.o decode_ENCRYPT_STORE.cc
g++ -I./ -c -o decode_TEST_WRITE_ADDRESS_update_TEST_address.o decode_TEST_WRITE_ADDRESS_update_TEST_address.cc
g++ -I./ -c -o decode_TEST_WRITE_ADDRESS_update_TEST_flag.o decode_TEST_WRITE_ADDRESS_update_TEST_flag.cc
g++ -I./ -c -o decode_TEST_START_ENCRYPT_update_TEST_status.o decode_TEST_START_ENCRYPT_update_TEST_status.cc
g++ -I./ -c -o decode_ENCRYPT_LOAD_update_ENCRYPT_byte_cnt.o decode_ENCRYPT_LOAD_update_ENCRYPT_byte_cnt.cc
g++ -I./ -c -o decode_ENCRYPT_LOAD_update_ENCRYPT_rd_data.o decode_ENCRYPT_LOAD_update_ENCRYPT_rd_data.cc
g++ -I./ -c -o decode_ENCRYPT_LOAD_update_TEST_status.o decode_ENCRYPT_LOAD_update_TEST_status.cc
g++ -I./ -c -o decode_ENCRYPT_ENC_update_ENCRYPT_enc_data.o decode_ENCRYPT_ENC_update_ENCRYPT_enc_data.cc
g++ -I./ -c -o decode_ENCRYPT_ENC_update_TEST_status.o decode_ENCRYPT_ENC_update_TEST_status.cc
g++ -I./ -c -o decode_ENCRYPT_STORE_update_TEST_XRAM.o decode_ENCRYPT_STORE_update_TEST_XRAM.cc
g++ -I./ -c -o decode_ENCRYPT_STORE_update_ENCRYPT_blk_cnt.o decode_ENCRYPT_STORE_update_ENCRYPT_blk_cnt.cc
g++ -I./ -c -o decode_ENCRYPT_STORE_update_ENCRYPT_byte_cnt.o decode_ENCRYPT_STORE_update_ENCRYPT_byte_cnt.cc
g++ -I./ -c -o decode_ENCRYPT_STORE_update_TEST_status.o decode_ENCRYPT_STORE_update_TEST_status.cc
g++ -I./ -c -o compute.o compute.cc 
g++ -I./ -c -o help.o ../../uninterpreted_func/uninterpreted_func.cc 
