path_classifiers:
  test:
    - tests

  docs:
    - docs

  script:
    - scripts

  example:
    - apps
    - examples

extraction:
  cpp:
    prepare:
      packages:
        - build-essential
        - libboost-all-dev
        - bison
        - flex
        - z3
        - libz3-dev

    configure:
      command:
        - cd $LGTM_SRC
        - mkdir -p build
        - cd build
        - cmake ..

    index:
      build_command:
        - make -j$(nproc)
