/// \file Parser for SMT-LIB2 generated by Yosys
/// the use of it is
///   1. translate data-type to bitvector declarations
///   2. add a no-change transition function
///   3. change variable name to their meaningful names

#ifndef YOSYS_SMT_PARSER_H__
#define YOSYS_SMT_PARSER_H__

#include <iostream>
#include <string>

namespace ilang {

/// \brief to parse an smt file
/// this will only work on the yosys's generated smt
/// and not on the assemblied CHC
class YosysSmtParser {
  // ---------------- TYPE DEFs -------------------- //
protected:
  /// the internal buffer
  std::string _buf;
  // ------------- HELPER FUNCTIONS ---------------- //
  /// parse the 
public:
  // -------------- CONSTRUCTOR -------------------- //
  YosysSmtParser(const std::string & buf);
}; // class YosysSmtParser

}; // namespace ilang

#endif