/// \file Parser for SMT-LIB2 generated by Yosys
/// the use of it is
///   1. translate data-type to bitvector declarations
///     a. datatype : recursively defined...
///     b. fix some 
///   2. add a no-change transition function
///   3. -- (currently no ) change variable name to their meaningful names

#include <ilang/smt-inout/yosys_smt_parser.h>

namespace ilang {





}; // namespace ilang