clean:
	-rm -f *.pyc
	-rm -f *~
	-rm -f cILA/*
	-rm -f vILA/*
	-rm -f AESsim
	-rm -f C/Cinst.c
	-rm -f C/test
	-rm -f test
	-rm -f info.txt
	-rm -f cex.out
	-rm -f assign.in result.out Cresult.out
	make clean -C Verilog
