name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: |
        cmake -E make_directory ${{github.workspace}}/deps
        cmake -E make_directory ${{github.workspace}}/build

    - name: Build and Install Dependency
      shell: bash
      run: source ${{github.workspace}}/scripts/setup-smtswitch.sh ${{github.workspace}} ${{github.workspace}}/deps

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake ${{github.workspace}} -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_PREFIX_PATH=${{github.workspace}}/deps

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: make -j$(nproc)

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: make run_test
